// Generated by CoffeeScript 1.6.3
(function() {
  this.Page = (function() {
    function Page(priority, type, name) {
      this.priority = priority;
      this.type = type;
      this.name = name != null ? name : null;
      this.originalPriority = this.priority;
      this.rect = new Rect();
      this.id = Math.random();
      this.idealArea = 0;
    }

    Page.prototype.isEqual = function(other) {
      if (other.id) {
        return this.id === other.id;
      } else {
        return false;
      }
    };

    return Page;

  })();

}).call(this);
