// Generated by CoffeeScript 1.6.3
(function() {
  this.Rect = (function() {
    function Rect(x, y, width, height) {
      this.x = x != null ? x : 0;
      this.y = y != null ? y : 0;
      this.width = width != null ? width : 0;
      this.height = height != null ? height : 0;
    }

    Rect.prototype.isEqual = function(other) {
      return this.x === other.x && this.y === other.y && this.width === other.width && this.height === other.height;
    };

    Rect.prototype.copy = function() {
      return new Rect(this.x, this.y, this.width, this.height);
    };

    Rect.prototype.area = function() {
      return this.width * this.height;
    };

    Rect.prototype.ratio = function() {
      return this.width / this.height;
    };

    Rect.prototype.vec4 = function() {
      return [this.x, this.y, this.width, this.height];
    };

    return Rect;

  })();

}).call(this);
