// Generated by CoffeeScript 1.6.3
(function() {
  var RectType;

  RectType = (function() {
    function RectType(ratio, minAlign) {
      this.ratio = ratio;
      this.minAlign = minAlign != null ? minAlign : 1;
    }

    return RectType;

  })();

  this.rectTypes = {
    'image': [new RectType(0.9, 1), new RectType(1.6, 1), new RectType(3.0, 2), new RectType(3.8, 2)],
    'text': [new RectType(3.8, 1), new RectType(1.0, 1)]
  };

}).call(this);
