// Generated by CoffeeScript 1.6.3
(function() {
  var DEFAULT_HEIGHT, DEFAULT_WIDTH;

  DEFAULT_WIDTH = 500;

  DEFAULT_HEIGHT = 500;

  this.Base = (function() {
    function Base(data, width, height, min_width, min_height) {
      this.width = width != null ? width : DEFAULT_WIDTH;
      this.height = height != null ? height : DEFAULT_HEIGHT;
      this.min_width = min_width != null ? min_width : 200;
      this.min_height = min_height != null ? min_height : 100;
      this.pageSets = this.createPageSets(data);
    }

    Base.prototype.createPageSets = function(data) {
      var d;
      return (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = data.length; _i < _len; _i++) {
          d = data[_i];
          _results.push(new Page(d.priority, d.type, d.name));
        }
        return _results;
      })();
    };

    Base.prototype.setIdealArea = function(pageSets) {
      var area, prioritySum;
      prioritySum = pageUtils.prioritySum(pageSets);
      area = this.width * this.height;
      return this.calcIdealArea(pageSets, area, prioritySum);
    };

    Base.prototype.calcIdealArea = function(pageSets, area, prioritySum) {
      var pageSet, _i, _len, _results;
      if (!pageUtils.isGroup(pageSets)) {
        return pageSets.idealArea = pageSets.priority * area / prioritySum;
      } else {
        _results = [];
        for (_i = 0, _len = pageSets.length; _i < _len; _i++) {
          pageSet = pageSets[_i];
          _results.push(this.calcIdealArea(pageSet, area, prioritySum));
        }
        return _results;
      }
    };

    return Base;

  })();

}).call(this);
