// Generated by CoffeeScript 1.6.3
(function() {
  this.data = [
    {
      priority: 10,
      type: "image"
    }, {
      priority: 9,
      type: "image"
    }, {
      priority: 8,
      type: "image"
    }, {
      priority: 7,
      type: "image"
    }, {
      priority: 6,
      type: "image"
    }, {
      priority: 5,
      type: "image"
    }, {
      priority: 4,
      type: "text"
    }, {
      priority: 3,
      type: "text"
    }, {
      priority: 2,
      type: "text"
    }, {
      priority: 1,
      type: "text"
    }
  ];

}).call(this);
