// Generated by CoffeeScript 1.6.3
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.GreedyLayout = (function(_super) {
    var arrange, arrangeTopLeft, split;

    __extends(GreedyLayout, _super);

    function GreedyLayout() {
      _ref = GreedyLayout.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    GreedyLayout.prototype.layout = function() {
      var g, groupSets, key, reverse, _i, _len, _results;
      groupSets = pageUtils.grouping(this.pageSets);
      pageUtils.deformPriorities(groupSets, this.width * this.height, this.min_width, this.min_height);
      this.setIdealArea(groupSets);
      pageUtils.sort(groupSets, reverse = true, key = function(a, b) {
        return pageUtils.avg(a) < pageUtils.avg(b);
      });
      _results = [];
      for (_i = 0, _len = groupSets.length; _i < _len; _i++) {
        g = groupSets[_i];
        _results.push(console.log(g));
      }
      return _results;
    };

    arrange = function(pageSets, rect) {
      if (pageSets.length < 1) {

      } else if (pageSets.length < 3) {
        return split(pageSets, rect);
      } else {
        return arrangeTopLeft(pageSets, rect);
      }
    };

    split = function(pageSet, rect) {
      var p;
      return p = 0;
    };

    arrangeTopLeft = function(pageSets, rect) {
      return a;
    };

    return GreedyLayout;

  })(Base);

}).call(this);
