// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var articles, data, hillClimbing, i, pageSets, paramArray, params, spparams, url, vol, _N, _height, _i, _j, _max, _ref, _width;
    data = [];
    url = location.href;
    params = url.split("?");
    spparams = params[1].split("&");
    paramArray = [];
    for (i = _i = 0, _ref = spparams.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
      vol = spparams[i].split("=");
      $('#param-form [name=' + vol[0] + ']').val(vol[1]);
    }
    _width = $('#param-form [name=width]').val() || 900;
    _height = $('#param-form [name=height]').val() || 500;
    _N = $('#param-form [name=N]').val() || 15;
    _max = $('#param-form [name=max-size]').val() || 100;
    console.log(_width);
    console.log(_N);
    for (i = _j = 0; 0 <= _N ? _j < _N : _j > _N; i = 0 <= _N ? ++_j : --_j) {
      data.push(new Page(Math.ceil(Math.random() * _max), "text"));
    }
    hillClimbing = new HillClimbing(null, data, _width, _height);
    hillClimbing.layout();
    pageSets = hillClimbing.pageSets;
    hillClimbing.climbing();
    return articles = d3.select("#main-container").selectAll("article").data(pageSets).enter().append("article").attr("class", "article").style("width", function(d) {
      return d.rect.width + "px";
    }).style("height", function(d) {
      return d.rect.height + "px";
    }).style("top", function(d) {
      return d.rect.y + "px";
    }).style("left", function(d) {
      return d.rect.x + "px";
    }).append("div").attr("class", "article-inner").text(function(d) {
      return d.originalPriority;
    });
  });

}).call(this);
