// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var articles, data, hillClimbing, i, pageSets, _i;
    data = [];
    for (i = _i = 0; _i < 10; i = ++_i) {
      data.push(new Page(Math.ceil(Math.random() * 100), "text"));
    }
    hillClimbing = new HillClimbing(null, data, 500, 300);
    hillClimbing.layout();
    pageSets = hillClimbing.pageSets;
    hillClimbing.climbing();
    return articles = d3.select("#main-container").selectAll("article").data(pageSets).enter().append("article").attr("class", "article").style("width", function(d) {
      return d.rect.width + "px";
    }).style("height", function(d) {
      return d.rect.height + "px";
    }).style("top", function(d) {
      return d.rect.y + "px";
    }).style("left", function(d) {
      return d.rect.x + "px";
    }).append("div").attr("class", "article-inner").text(function(d) {
      return d.originalPriority;
    });
  });

}).call(this);
