// Generated by CoffeeScript 1.6.3
(function() {
  describe("model/page", function() {
    it("Create page object", function() {
      var page;
      page = new Page(10, "image");
      expect(page.originalPriority).toEqual(10);
      expect(page.type).toEqual("image");
      return expect(page.name).toBe(null);
    });
    return describe("isEqual function", function() {
      var page_1, page_2;
      page_1 = new Page(10, "image");
      page_2 = new Page(10, "image");
      it("Equal", function() {
        var page_1_2;
        page_1_2 = page_1;
        return expect(page_1.isEqual(page_1_2)).toBe(true);
      });
      return it("Not equal", function() {
        return expect(page_1.isEqual(page_2)).toBe(false);
      });
    });
  });

}).call(this);
