// Generated by CoffeeScript 1.6.3
(function() {
  describe("model/rect_type", function() {
    return it("rectTypes", function() {
      expect(rectTypes["image"].length).toEqual(4);
      return expect(rectTypes["image"][0].min_align).toEqual(1);
    });
  });

}).call(this);
