// Generated by CoffeeScript 1.6.3
(function() {
  describe("model/rect_type", function() {
    return it("rect_types", function() {
      expect(rect_types["image"].length).toEqual(4);
      return expect(rect_types["image"][0].min_align).toEqual(1);
    });
  });

}).call(this);
