// Generated by CoffeeScript 1.6.3
(function() {
  describe("base", function() {
    beforeEach(function() {
      this.d = [
        {
          priority: 10,
          type: "image"
        }, {
          priority: 20,
          type: "text"
        }
      ];
      return this.base = new Base(this.d, 500, 500);
    });
    it("initialize", function() {
      expect(this.base.pageSets[1].originalPriority).toEqual(20);
      return expect(this.base.pageSets[0].type).toEqual(this.d[0].type);
    });
    return it("setIdealArea", function() {
      this.base.setIdealArea(this.base.pageSets);
      return expect(this.base.pageSets[0].idealArea > (500 * 500 - 1) / 3).toBeTruthy();
    });
  });

}).call(this);
