// Generated by CoffeeScript 1.6.3
(function() {
  describe("page-utils", function() {
    beforeEach(function() {
      this.d = [
        {
          priority: 10,
          type: "text"
        }, {
          priority: 11,
          type: "text"
        }, {
          priority: 20,
          type: "text"
        }
      ];
      return this.layout = new GreedyLayout(this.d, 500, 600);
    });
    return it("layout", function() {
      return this.layout.layout();
    });
  });

}).call(this);
